### ISSUE TITLE
Cant connect to Host from Raspberry Pi 4

### ISSUE THREAD

**Issue by GoProProfi** [reallyinsane/trainsimulator-controller#5]
I have installed java on the Raspberry Pi and it works.

I compiled the prject with OpenJDK11 and the java version on the Pi is the same. 
I tried to run the "trainsimulator-rasperry-1.1.0.jar" i get the following Output:
` `
 :: Spring Boot ::        (v2.2.2.RELEASE)

2021-10-29 22:43:47.949  INFO 4973 --- [           main] i.m.t.raspberry.RaspberryApplication     : Starting RaspberryApplication v1.1.0 on raspberrypi with PID 4973 (/home/pi/java/trainsimulator-raspberry-1.1.0.jar started by pi in /home/pi/java)
2021-10-29 22:43:47.959  INFO 4973 --- [           main] i.m.t.raspberry.RaspberryApplication     : The following profiles are active: client
2021-10-29 22:43:51.334  INFO 4973 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'trainsimulatorConfiguration' of type [io.mathan.trainsimulator.client.TrainsimulatorConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-10-29 22:43:54.831  WARN 4973 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'service' defined in URL [jar:file:/home/pi/java/trainsimulator-raspberry-1.1.0.jar!/BOOT-INF/lib/trainsimulator-core-1.1.0.jar!/io/mathan/trainsimulator/service/Service.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'restConnector' defined in URL [jar:file:/home/pi/java/trainsimulator-raspberry-1.1.0.jar!/BOOT-INF/lib/trainsimulator-client-1.1.0.jar!/io/mathan/trainsimulator/client/RestConnector.class]: Invocation of init method failed; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://DESKTOP-T3Q6VU0:8000/trainsimulator/generic": Keine Route zum Zielrechner (Host unreachable); nested exception is java.net.NoRouteToHostException: Keine Route zum Zielrechner (Host unreachable)
2021-10-29 22:43:54.932  INFO 4973 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-10-29 22:43:54.952 ERROR 4973 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'service' defined in URL [jar:file:/home/pi/java/trainsimulator-raspberry-1.1.0.jar!/BOOT-INF/lib/trainsimulator-core-1.1.0.jar!/io/mathan/trainsimulator/service/Service.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'restConnector' defined in URL [jar:file:/home/pi/java/trainsimulator-raspberry-1.1.0.jar!/BOOT-INF/lib/trainsimulator-client-1.1.0.jar!/io/mathan/trainsimulator/client/RestConnector.class]: Invocation of init method failed; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://DESKTOP-T3Q6VU0:8000/trainsimulator/generic": Keine Route zum Zielrechner (Host unreachable); nested exception is java.net.NoRouteToHostException: Keine Route zum Zielrechner (Host unreachable)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:240) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:722) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:535) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
        at io.mathan.trainsimulator.raspberry.RaspberryApplication.main(RaspberryApplication.java:28) ~[classes!/:1.1.0]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[trainsimulator-raspberry-1.1.0.jar:1.1.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[trainsimulator-raspberry-1.1.0.jar:1.1.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[trainsimulator-raspberry-1.1.0.jar:1.1.0]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[trainsimulator-raspberry-1.1.0.jar:1.1.0]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'restConnector' defined in URL [jar:file:/home/pi/java/trainsimulator-raspberry-1.1.0.jar!/BOOT-INF/lib/trainsimulator-client-1.1.0.jar!/io/mathan/trainsimulator/client/RestConnector.class]: Invocation of init method failed; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://DESKTOP-T3Q6VU0:8000/trainsimulator/generic": Keine Route zum Zielrechner (Host unreachable); nested exception is java.net.NoRouteToHostException: Keine Route zum Zielrechner (Host unreachable)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        ... 27 common frames omitted
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://DESKTOP-T3Q6VU0:8000/trainsimulator/generic": Keine Route zum Zielrechner (Host unreachable); nested exception is java.net.NoRouteToHostException: Keine Route zum Zielrechner (Host unreachable)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:751) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:677) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:345) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at io.mathan.trainsimulator.client.RestConnector.getGenericLocomotive(RestConnector.java:69) ~[trainsimulator-client-1.1.0.jar!/:1.1.0]
        at io.mathan.trainsimulator.client.RestConnector.afterPropertiesSet(RestConnector.java:78) ~[trainsimulator-client-1.1.0.jar!/:1.1.0]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        ... 38 common frames omitted
Caused by: java.net.NoRouteToHostException: Keine Route zum Zielrechner (Host unreachable)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:609) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:558) ~[na:na]
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015) ~[na:na]
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:76) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:742) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
        ... 44 common frames omitted
``

I have no idea.
I had to change the trainsimulator.hos Variable in the application.properties for the Pi. Alsow i changed the Port to 8000 in both Pi and Server.

I think the problem lies about:
`I/O error on GET request for "http://DESKTOP-T3Q6VU0:8000/trainsimulator/generic": Keine Route zum Zielrechner (Host unreachable); nested exception is java.net.NoRouteToHostException: Keine Route zum Zielrechner (Host unreachable)`

**Comment by reallyinsane** [comment]
Hi,

in the raspberry project the trainsimulator.host and the trainsimulator.port are describing the location of trainsimulator-server running. The trainsimulator must be up and running to be able to connect. In the trainsimulator-server project the default port (server.port) is 13913. If you change the port you have to change it in both locations.

 If you started trainsimulator-server you can check if it is running by opening the URL http://DESKTOP-T3Q6VU0:8000/trainsimulator/generic in your browser. You should get an response then. You could also check if you can ping DESKTOP-T3Q6VU0 from the raspberry. Sometimes the name can not be resolved, try the IP address then.

Hope that hepls.

Regards,

Matthias

**Comment by GoProProfi** [comment]
Thanks for teh quik Answer.
Changin to the IP Adress Solved it vor me.
